# Generated by Django 5.2.1 on 2025-07-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_email',
        ),
    ]
