# Generated by Django 5.2.1 on 2025-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requires_delivery',
            field=models.BooleanField(default=False, verbose_name='Вид почты'),
        ),
    ]
