# Generated by Django 5.2.1 on 2025-07-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_requires_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requires_delivery',
            field=models.CharField(verbose_name='Вид почты'),
        ),
    ]
