# Generated by Django 5.2.1 on 2025-07-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_requires_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=25, verbose_name='Номер телефона'),
        ),
    ]
