# Generated by Django 5.2.1 on 2025-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Лидер продаж'),
        ),
    ]
