from __future__ import annotations

import os
from typing import Optional

from django import template
from django.core.files.storage import default_storage
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from django.templatetags.static import static
from django.contrib.staticfiles import finders

register = template.Library()


@register.simple_tag
def product_image_picture(product, size: str = "400x300", classes: str = "", alt: Optional[str] = None,
                         width: int = 400, height: int = 300, loading: str = "lazy"):
    """
    Render a <picture> for product image with AVIF/WebP priority and fallback to original.
    Usage:
      {% product_image_picture product '400x300' 'product-card-img' product.name 400 300 'lazy' %}
    """
    alt_attr = alt or getattr(product, "name", "")
    class_attr = classes or ""
    
    # Try main product image first
    img_field = getattr(product, "image", None)
    if not img_field or not getattr(img_field, "name", ""):
        # Try first additional image
        try:
            images = getattr(product, "images", None)
            if images and images.exists():
                img_field = images.first().image
        except Exception:
            pass
    
    if img_field and getattr(img_field, "name", ""):
        orig_url = getattr(img_field, "url", None)
        if callable(orig_url):
            try:
                orig_url = img_field.url
            except Exception:
                orig_url = None

        if orig_url:
            name = img_field.name
            avif_name = _variant_name(name, size, "avif")
            webp_name = _variant_name(name, size, "webp")

            avif_url = _url_if_exists(avif_name)
            webp_url = _url_if_exists(webp_name)

            parts = ["<picture>"]
            if avif_url:
                parts.append(f"<source srcset=\"{avif_url}\" type=\"image/avif\">")
            if webp_url:
                parts.append(f"<source srcset=\"{webp_url}\" type=\"image/webp\">")
            # Fallback to original
            parts.append(
                f"<img src=\"{orig_url}\" alt=\"{alt_attr}\" class=\"{class_attr}\" width=\"{width}\" height=\"{height}\" loading=\"{loading}\" decoding=\"async\">"
            )
            parts.append("</picture>")
            return mark_safe("".join(parts))

    # Ultimate fallback to placeholder
    fallback = static("deps/images/placeholder.png")
    return mark_safe(
        f"<img src=\"{fallback}\" alt=\"{alt_attr}\" class=\"{class_attr}\" width=\"{width}\" height=\"{height}\" loading=\"{loading}\" decoding=\"async\">"
    )


def _variant_name(orig_name: str, size: str, ext: str) -> str:
    root, _ext = os.path.splitext(orig_name)
    return f"{root}_{size}.{ext}"


def _url_if_exists(name: str) -> Optional[str]:
    try:
        if default_storage.exists(name):
            return default_storage.url(name)
    except Exception:
        return None
    return None


@register.simple_tag
def category_icon_picture(category, size: str = "128x128", classes: str = "", alt: Optional[str] = None,
                          width: int = 128, height: int = 128):
    """
    Render a <picture> for category.image with AVIF/WebP priority and fallback to original.
    Usage:
      {% category_icon_picture category '128x128' 'catalog-category-icon' category.name 128 128 %}
    """
    img_field = getattr(category, "image", None)
    alt_attr = alt or getattr(category, "name", "")
    class_attr = classes or ""

    # 1) Prefer media-based image from admin with our generated variants
    if img_field and getattr(img_field, "name", ""):
        orig_url = getattr(img_field, "url", None)
        if callable(orig_url):
            try:
                orig_url = img_field.url
            except Exception:
                orig_url = None

        name = img_field.name
        avif_name = _variant_name(name, size, "avif")
        webp_name = _variant_name(name, size, "webp")

        avif_url = _url_if_exists(avif_name)
        webp_url = _url_if_exists(webp_name)

        parts = ["<picture>"]
        if avif_url:
            parts.append(f"<source srcset=\"{avif_url}\" type=\"image/avif\">")
        if webp_url:
            parts.append(f"<source srcset=\"{webp_url}\" type=\"image/webp\">")
        # Fallback to original media image
        if orig_url:
            parts.append(
                f"<img src=\"{orig_url}\" alt=\"{alt_attr}\" class=\"{class_attr}\" width=\"{width}\" height=\"{height}\" loading=\"lazy\" decoding=\"async\">"
            )
        parts.append("</picture>")
        return mark_safe("".join(parts))

    # 2) Fallback to static icon by slug (if exists)
    slug = getattr(category, "slug", "")
    if slug:
        static_base = f"deps/icons/{slug}"
        # Try with size suffix first (generated by generate_category_icons command)
        static_avif_sized = f"{static_base}_{size}.avif"
        static_webp_sized = f"{static_base}_{size}.webp"
        # Fallback to files without size suffix
        static_avif = f"{static_base}.avif"
        static_webp = f"{static_base}.webp"
        static_png = f"{static_base}.png"
        
        # Check for sized variants first, then fallback to non-sized
        has_avif = bool(finders.find(static_avif_sized)) or bool(finders.find(static_avif))
        has_webp = bool(finders.find(static_webp_sized)) or bool(finders.find(static_webp))
        has_png = bool(finders.find(static_png))
        
        # Use the actual found files
        final_avif = static_avif_sized if finders.find(static_avif_sized) else static_avif
        final_webp = static_webp_sized if finders.find(static_webp_sized) else static_webp
        if has_avif or has_webp or has_png:
            parts = ["<picture>"]
            if has_avif:
                parts.append(f"<source srcset=\"{ static(final_avif) }\" type=\"image/avif\">")
            if has_webp:
                parts.append(f"<source srcset=\"{ static(final_webp) }\" type=\"image/webp\">")
            fallback = static(static_png) if has_png else (static(final_webp) if has_webp else static(final_avif))
            parts.append(
                f"<img src=\"{fallback}\" alt=\"{alt_attr}\" class=\"{class_attr}\" width=\"{width}\" height=\"{height}\" loading=\"lazy\" decoding=\"async\">"
            )
            parts.append("</picture>")
            return mark_safe("".join(parts))

    # 3) Ultimate placeholder
    fallback = static("deps/images/placeholder.png")
    return mark_safe(
        f"<img src=\"{fallback}\" alt=\"{alt_attr}\" class=\"{class_attr}\" width=\"{width}\" height=\"{height}\" loading=\"lazy\" decoding=\"async\">"
    )
